FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    libpq-dev

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gzip zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

RUN groupadd -g 1000 www && useradd -u 1000 -ms /bin/bash -g www www

COPY . /var/www/html

RUN chown -R www:www /var/www/html

USER www

EXPOSE 9000

CMD ["php-fpm"]